language: node_js
node_js:
- stable
before_script:
  - npm install
  - npm install --save gulp -g
  - npm install --save gulp-qunit -g
script: bash ./deploy.sh
env:
  global:
  - ENCRYPTION_LABEL: "<.... encryption label from previous step ....>"
  - COMMIT_AUTHOR_EMAIL: "mehmeterenyener@gmail.com"
